### PR TITLE
Adds TS typedefs so typed projects can inference

### PR DESCRIPTION
**Pull request by Gozala**
Hey @pgte would you mind taking this change ? It makes this lib more usable for projects that use typescript and also improves experience when used as dependency in VSCode allowing it to provide better intelisence.

### CODE REVIEW

**Review by pgte — APPROVED** [review]

**Comment by pgte** [comment]
That looks good.
@Gozala Do you mind if I add you as maintainer if this package?

**Comment by achingbrain** [comment]
@pgte anything stopping this and #8 (for the ci fix mainly) being merged and released?  Happy to be added as a maintainer or @Gozala, which ever is easier 😄

**Comment by Gozala** [comment]
>  @Gozala Do you mind if I add you as maintainer if this package?

Sure thanks! If you do not want to maintain this package anymore it might be worth transferring it to PL ?

**Comment by pgte** [comment]
@Gozala thanks! Landed on v1.0.1.

**Pull request merged**
